@startuml solutionISP
interface IDoor {
    + lock()
    + unlock()
    + open()
    + close()
}

interface ITimed {
    + timeOutCallback()
}

interface ISensing {
    + proximityCallback()
}

class SensingDoor {
}

class TimedDoor {
}

class Sensor {
    + register(Sensing sensingDoor)
}

class Timer {
    + register(timeOut, Timed timedDoor)
}

IDoor <|.. SensingDoor
IDoor <|.. TimedDoor
ISensing <|.. SensingDoor
ITimed <|.. TimedDoor
Sensor ..> ISensing
Timer ..> ITimed
@enduml
